import { getDb } from './connection';

interface RecipeSeed {
  id: string;
  name: string;
  category: 'breakfast' | 'prep' | 'dinner_main' | 'dinner_side' | 'soup';
  cooking_time_min: number;
  calories: number;
  salt_g: number;
  carbs_g: number;
  protein_g: number;
  fiber_g: number;
  potassium_mg: number;
  ingredients: { name: string; amount: string }[];
  steps: string[];
  salt_tips: string[];
  sugar_tips: string[];
}

const recipes: RecipeSeed[] = [
  // === 朝食（15分以内） ===
  {
    id: 'breakfast-001',
    name: 'だし巻き卵（薄味）',
    category: 'breakfast',
    cooking_time_min: 10,
    calories: 150,
    salt_g: 0.8,
    carbs_g: 2,
    protein_g: 12,
    fiber_g: 0,
    potassium_mg: 130,
    ingredients: [
      { name: '卵', amount: '2個' },
      { name: 'だし汁', amount: '大さじ2' },
      { name: '薄口醤油', amount: '小さじ1/2' },
      { name: 'みりん', amount: '小さじ1/2' },
    ],
    steps: [
      '卵を溶きほぐし、だし汁と調味料を加えて混ぜる',
      '卵焼き器を中火で熱し、油をなじませる',
      '卵液を3回に分けて流し入れ、巻いていく',
      '形を整えて完成',
    ],
    salt_tips: ['醤油は減塩醤油でもOK', 'だしを濃くすることで薄味でも満足感UP'],
    sugar_tips: [],
  },
  {
    id: 'breakfast-002',
    name: '納豆ご飯セット',
    category: 'breakfast',
    cooking_time_min: 5,
    calories: 350,
    salt_g: 0.6,
    carbs_g: 45,
    protein_g: 15,
    fiber_g: 4,
    potassium_mg: 400,
    ingredients: [
      { name: 'ご飯', amount: '100g' },
      { name: '納豆', amount: '1パック' },
      { name: '青ネギ', amount: '少々' },
      { name: '海苔', amount: '1枚' },
    ],
    steps: [
      '納豆を付属のタレなしでよく混ぜる',
      'ご飯に納豆をのせ、青ネギを散らす',
      '海苔を添えて完成',
    ],
    salt_tips: ['付属のタレは塩分が多いので使わない', 'からしや酢で風味付け'],
    sugar_tips: ['ご飯は100gに抑える', '野菜を先に食べる'],
  },
  {
    id: 'breakfast-003',
    name: 'ほうれん草のおひたし',
    category: 'breakfast',
    cooking_time_min: 8,
    calories: 30,
    salt_g: 0.5,
    carbs_g: 2,
    protein_g: 3,
    fiber_g: 3,
    potassium_mg: 550,
    ingredients: [
      { name: 'ほうれん草', amount: '1/2束' },
      { name: 'だし汁', amount: '大さじ1' },
      { name: '薄口醤油', amount: '小さじ1/2' },
      { name: 'かつお節', amount: '少々' },
    ],
    steps: [
      'ほうれん草を塩なしで茹でる',
      '冷水にとり、水気をしっかり絞る',
      '3cm長さに切り、だし汁と醤油で和える',
      'かつお節をかけて完成',
    ],
    salt_tips: ['茹でる時に塩を入れない', '醤油は控えめ、だしの旨味で食べる'],
    sugar_tips: [],
  },
  {
    id: 'breakfast-004',
    name: '具沢山味噌汁（減塩）',
    category: 'breakfast',
    cooking_time_min: 12,
    calories: 80,
    salt_g: 1.0,
    carbs_g: 8,
    protein_g: 5,
    fiber_g: 3,
    potassium_mg: 400,
    ingredients: [
      { name: '豆腐', amount: '1/4丁' },
      { name: 'わかめ', amount: '少々' },
      { name: '長ネギ', amount: '1/4本' },
      { name: '味噌', amount: '大さじ1' },
      { name: 'だしパック', amount: '2パック' },
      { name: '水', amount: '300ml' },
    ],
    steps: [
      'だしパック2つで濃いめにだしを取る',
      '豆腐、わかめ、ネギを入れて温める',
      '火を止めてから味噌を溶き入れる',
    ],
    salt_tips: ['だしパックを2倍使い、味噌を半量に', '具材を多くして満足感UP'],
    sugar_tips: [],
  },
  {
    id: 'breakfast-005',
    name: 'バナナヨーグルト',
    category: 'breakfast',
    cooking_time_min: 3,
    calories: 150,
    salt_g: 0.1,
    carbs_g: 28,
    protein_g: 5,
    fiber_g: 2,
    potassium_mg: 500,
    ingredients: [
      { name: 'バナナ', amount: '1本' },
      { name: 'プレーンヨーグルト', amount: '100g' },
      { name: 'くるみ', amount: '2粒' },
    ],
    steps: [
      'バナナを輪切りにする',
      'ヨーグルトにバナナを入れる',
      'くるみを砕いてトッピング',
    ],
    salt_tips: [],
    sugar_tips: ['バナナは血糖値を上げるので食後に', '砂糖は加えない'],
  },
  {
    id: 'breakfast-006',
    name: '温泉卵のせ冷奴',
    category: 'breakfast',
    cooking_time_min: 5,
    calories: 120,
    salt_g: 0.4,
    carbs_g: 3,
    protein_g: 12,
    fiber_g: 1,
    potassium_mg: 200,
    ingredients: [
      { name: '絹ごし豆腐', amount: '1/2丁' },
      { name: '温泉卵', amount: '1個' },
      { name: 'かつお節', amount: '少々' },
      { name: '減塩醤油', amount: '小さじ1' },
    ],
    steps: [
      '豆腐を器に盛る',
      '温泉卵をのせる',
      'かつお節と醤油をかける',
    ],
    salt_tips: ['減塩醤油を使用', 'ポン酢でもOK'],
    sugar_tips: [],
  },
  {
    id: 'breakfast-007',
    name: 'アボカドトースト（減塩）',
    category: 'breakfast',
    cooking_time_min: 8,
    calories: 280,
    salt_g: 0.7,
    carbs_g: 25,
    protein_g: 8,
    fiber_g: 6,
    potassium_mg: 500,
    ingredients: [
      { name: '全粒粉パン', amount: '1枚' },
      { name: 'アボカド', amount: '1/2個' },
      { name: 'レモン汁', amount: '小さじ1' },
      { name: '黒こしょう', amount: '少々' },
    ],
    steps: [
      'パンをトーストする',
      'アボカドをフォークで潰し、レモン汁を混ぜる',
      'パンに塗り、黒こしょうをふる',
    ],
    salt_tips: ['塩は使わずレモンと胡椒で', 'アボカドはカリウム豊富'],
    sugar_tips: ['全粒粉パンで食物繊維UP'],
  },
  {
    id: 'breakfast-008',
    name: '鮭フレークおにぎり',
    category: 'breakfast',
    cooking_time_min: 5,
    calories: 200,
    salt_g: 0.8,
    carbs_g: 35,
    protein_g: 8,
    fiber_g: 1,
    potassium_mg: 150,
    ingredients: [
      { name: 'ご飯', amount: '100g' },
      { name: '減塩鮭フレーク', amount: '大さじ1' },
      { name: '白ごま', amount: '少々' },
      { name: '海苔', amount: '1枚' },
    ],
    steps: [
      'ご飯に鮭フレークと白ごまを混ぜる',
      'おにぎりに成形',
      '海苔を巻く',
    ],
    salt_tips: ['減塩タイプの鮭フレークを選ぶ'],
    sugar_tips: ['ご飯は100gに抑える'],
  },
  {
    id: 'breakfast-009',
    name: 'ほうれん草入りスクランブルエッグ',
    category: 'breakfast',
    cooking_time_min: 10,
    calories: 180,
    salt_g: 0.5,
    carbs_g: 3,
    protein_g: 14,
    fiber_g: 2,
    potassium_mg: 400,
    ingredients: [
      { name: '卵', amount: '2個' },
      { name: 'ほうれん草', amount: '1/4束' },
      { name: '牛乳', amount: '大さじ1' },
      { name: 'こしょう', amount: '少々' },
      { name: 'オリーブオイル', amount: '小さじ1' },
    ],
    steps: [
      'ほうれん草は1cm幅に切り、レンジで1分加熱',
      '卵を溶き、牛乳とこしょうを加える',
      'フライパンで炒め、半熟で火を止める',
    ],
    salt_tips: ['塩は使わずこしょうで風味付け'],
    sugar_tips: [],
  },
  {
    id: 'breakfast-010',
    name: 'しらすおろし',
    category: 'breakfast',
    cooking_time_min: 5,
    calories: 50,
    salt_g: 0.8,
    carbs_g: 4,
    protein_g: 6,
    fiber_g: 1,
    potassium_mg: 180,
    ingredients: [
      { name: '大根おろし', amount: '50g' },
      { name: 'しらす', amount: '大さじ1' },
      { name: '酢', amount: '小さじ1' },
    ],
    steps: [
      '大根をおろす',
      'しらすをのせる',
      '酢をかけて完成',
    ],
    salt_tips: ['しらすに塩分があるので醤油は不要', '酢で爽やかに'],
    sugar_tips: [],
  },

  // === 作り置き（30分以内） ===
  {
    id: 'prep-001',
    name: '切り干し大根煮（減塩）',
    category: 'prep',
    cooking_time_min: 25,
    calories: 80,
    salt_g: 0.8,
    carbs_g: 12,
    protein_g: 3,
    fiber_g: 4,
    potassium_mg: 500,
    ingredients: [
      { name: '切り干し大根', amount: '30g' },
      { name: '人参', amount: '1/4本' },
      { name: '油揚げ', amount: '1/2枚' },
      { name: 'だし汁', amount: '200ml' },
      { name: '薄口醤油', amount: '小さじ1' },
      { name: 'みりん', amount: '小さじ1' },
    ],
    steps: [
      '切り干し大根を水で戻し、食べやすい長さに切る',
      '人参は千切り、油揚げは短冊切り',
      'だし汁で煮て、調味料を加え汁気がなくなるまで煮る',
    ],
    salt_tips: ['だしを濃くして醤油を減らす', '戻し汁もだしとして使う'],
    sugar_tips: [],
  },
  {
    id: 'prep-002',
    name: 'ひじきの煮物（減塩）',
    category: 'prep',
    cooking_time_min: 25,
    calories: 70,
    salt_g: 0.7,
    carbs_g: 8,
    protein_g: 4,
    fiber_g: 5,
    potassium_mg: 600,
    ingredients: [
      { name: '乾燥ひじき', amount: '15g' },
      { name: '人参', amount: '1/4本' },
      { name: '大豆水煮', amount: '50g' },
      { name: 'だし汁', amount: '150ml' },
      { name: '薄口醤油', amount: '小さじ1' },
      { name: 'みりん', amount: '小さじ1' },
    ],
    steps: [
      'ひじきを水で戻す',
      '人参は千切りにする',
      'だし汁で煮て、調味料で味付け',
    ],
    salt_tips: ['だしを効かせて醤油控えめ', 'カリウム豊富で血圧対策に'],
    sugar_tips: [],
  },
  {
    id: 'prep-003',
    name: '酢きんぴら',
    category: 'prep',
    cooking_time_min: 15,
    calories: 60,
    salt_g: 0.5,
    carbs_g: 10,
    protein_g: 1,
    fiber_g: 3,
    potassium_mg: 250,
    ingredients: [
      { name: 'ごぼう', amount: '1/2本' },
      { name: '人参', amount: '1/4本' },
      { name: '酢', amount: '大さじ1' },
      { name: '薄口醤油', amount: '小さじ1/2' },
      { name: 'ごま油', amount: '小さじ1' },
      { name: '白ごま', amount: '少々' },
    ],
    steps: [
      'ごぼうと人参を細切りにする',
      'ごま油で炒め、酢と醤油で味付け',
      '白ごまをふって完成',
    ],
    salt_tips: ['酢を使うことで醤油を大幅カット', '酸味で満足感UP'],
    sugar_tips: ['ごぼうは食物繊維豊富'],
  },
  {
    id: 'prep-004',
    name: '蒸し鶏',
    category: 'prep',
    cooking_time_min: 25,
    calories: 150,
    salt_g: 0.5,
    carbs_g: 1,
    protein_g: 25,
    fiber_g: 0,
    potassium_mg: 300,
    ingredients: [
      { name: '鶏むね肉', amount: '1枚' },
      { name: '長ネギの青い部分', amount: '1本分' },
      { name: '生姜スライス', amount: '3枚' },
      { name: '酒', amount: '大さじ2' },
    ],
    steps: [
      '鶏肉をフォークで数カ所刺す',
      '耐熱皿に鶏肉、ネギ、生姜、酒を入れラップ',
      '600Wで5分加熱、裏返して3分加熱',
      '粗熱が取れたらスライス',
    ],
    salt_tips: ['塩を使わず酒と生姜で風味付け', 'ポン酢やごまだれで食べる'],
    sugar_tips: ['たんぱく質豊富で筋肉維持に'],
  },
  {
    id: 'prep-005',
    name: 'ほうれん草のナムル',
    category: 'prep',
    cooking_time_min: 10,
    calories: 50,
    salt_g: 0.4,
    carbs_g: 3,
    protein_g: 3,
    fiber_g: 3,
    potassium_mg: 500,
    ingredients: [
      { name: 'ほうれん草', amount: '1束' },
      { name: 'ごま油', amount: '小さじ1' },
      { name: 'すりごま', amount: '大さじ1' },
      { name: 'にんにく（すりおろし）', amount: '少々' },
    ],
    steps: [
      'ほうれん草を茹でて冷水にとる',
      '水気を絞り3cm長さに切る',
      '調味料で和える',
    ],
    salt_tips: ['塩を使わずにんにくとごまで風味付け'],
    sugar_tips: [],
  },
  {
    id: 'prep-006',
    name: 'きゅうりとわかめの酢の物',
    category: 'prep',
    cooking_time_min: 10,
    calories: 25,
    salt_g: 0.5,
    carbs_g: 5,
    protein_g: 1,
    fiber_g: 2,
    potassium_mg: 200,
    ingredients: [
      { name: 'きゅうり', amount: '1本' },
      { name: '乾燥わかめ', amount: '小さじ1' },
      { name: '酢', amount: '大さじ1' },
      { name: '砂糖', amount: '小さじ1/2' },
      { name: '薄口醤油', amount: '小さじ1/2' },
    ],
    steps: [
      'きゅうりを薄切りにする',
      'わかめを水で戻す',
      '調味料で和える',
    ],
    salt_tips: ['酢をメインに醤油は風味付け程度'],
    sugar_tips: ['砂糖は少量に'],
  },
  {
    id: 'prep-007',
    name: 'にんじんしりしり',
    category: 'prep',
    cooking_time_min: 15,
    calories: 100,
    salt_g: 0.6,
    carbs_g: 8,
    protein_g: 6,
    fiber_g: 2,
    potassium_mg: 300,
    ingredients: [
      { name: '人参', amount: '1本' },
      { name: '卵', amount: '1個' },
      { name: 'ツナ缶（水煮）', amount: '1/2缶' },
      { name: '薄口醤油', amount: '小さじ1/2' },
      { name: 'ごま油', amount: '小さじ1' },
    ],
    steps: [
      '人参を千切りにする',
      'ごま油で炒め、ツナを加える',
      '溶き卵を入れて炒め合わせ、醤油で味付け',
    ],
    salt_tips: ['ツナは水煮タイプを選ぶ'],
    sugar_tips: [],
  },
  {
    id: 'prep-008',
    name: 'もやしのナムル',
    category: 'prep',
    cooking_time_min: 8,
    calories: 40,
    salt_g: 0.3,
    carbs_g: 3,
    protein_g: 2,
    fiber_g: 2,
    potassium_mg: 150,
    ingredients: [
      { name: 'もやし', amount: '1袋' },
      { name: 'ごま油', amount: '小さじ1' },
      { name: 'すりごま', amount: '大さじ1' },
      { name: 'にんにく（すりおろし）', amount: '少々' },
    ],
    steps: [
      'もやしをさっと茹でる',
      '水気を切り、調味料で和える',
    ],
    salt_tips: ['塩を使わずにんにくとごまの風味で'],
    sugar_tips: [],
  },
  {
    id: 'prep-009',
    name: '小松菜の煮浸し',
    category: 'prep',
    cooking_time_min: 12,
    calories: 40,
    salt_g: 0.6,
    carbs_g: 4,
    protein_g: 3,
    fiber_g: 2,
    potassium_mg: 400,
    ingredients: [
      { name: '小松菜', amount: '1束' },
      { name: '油揚げ', amount: '1/2枚' },
      { name: 'だし汁', amount: '100ml' },
      { name: '薄口醤油', amount: '小さじ1' },
      { name: 'みりん', amount: '小さじ1/2' },
    ],
    steps: [
      '小松菜を3cm長さに切る',
      '油揚げは短冊切り',
      'だし汁で煮て調味料で味付け',
    ],
    salt_tips: ['だしを効かせて醤油控えめ'],
    sugar_tips: [],
  },
  {
    id: 'prep-010',
    name: 'かぼちゃの煮物（薄味）',
    category: 'prep',
    cooking_time_min: 20,
    calories: 90,
    salt_g: 0.4,
    carbs_g: 18,
    protein_g: 2,
    fiber_g: 3,
    potassium_mg: 400,
    ingredients: [
      { name: 'かぼちゃ', amount: '200g' },
      { name: 'だし汁', amount: '150ml' },
      { name: '薄口醤油', amount: '小さじ1/2' },
      { name: 'みりん', amount: '小さじ1' },
    ],
    steps: [
      'かぼちゃを一口大に切る',
      'だし汁で柔らかくなるまで煮る',
      '調味料を加えて煮含める',
    ],
    salt_tips: ['かぼちゃの自然な甘みを活かす', '醤油は風味付け程度'],
    sugar_tips: ['かぼちゃは糖質が多め、量に注意'],
  },

  // === 夕食メイン（60分以内） ===
  {
    id: 'dinner-main-001',
    name: '鮭のホイル焼き（レモン風味）',
    category: 'dinner_main',
    cooking_time_min: 25,
    calories: 200,
    salt_g: 1.0,
    carbs_g: 5,
    protein_g: 22,
    fiber_g: 2,
    potassium_mg: 450,
    ingredients: [
      { name: '生鮭', amount: '1切れ' },
      { name: '玉ねぎ', amount: '1/4個' },
      { name: 'しめじ', amount: '1/4パック' },
      { name: 'レモン', amount: '2切れ' },
      { name: 'バター', amount: '5g' },
      { name: '薄口醤油', amount: '小さじ1/2' },
    ],
    steps: [
      'アルミホイルに玉ねぎスライスを敷く',
      '鮭、しめじ、レモンをのせる',
      'バターを落とし、醤油を垂らす',
      'ホイルを閉じてフライパンで15分蒸し焼き',
    ],
    salt_tips: ['レモンの酸味で塩分控えめでも満足', '塩鮭ではなく生鮭を使う'],
    sugar_tips: [],
  },
  {
    id: 'dinner-main-002',
    name: '豆腐ハンバーグ',
    category: 'dinner_main',
    cooking_time_min: 30,
    calories: 250,
    salt_g: 1.2,
    carbs_g: 10,
    protein_g: 20,
    fiber_g: 2,
    potassium_mg: 350,
    ingredients: [
      { name: '木綿豆腐', amount: '150g' },
      { name: '鶏ひき肉', amount: '100g' },
      { name: '玉ねぎ', amount: '1/4個' },
      { name: 'パン粉', amount: '大さじ2' },
      { name: '卵', amount: '1/2個' },
      { name: 'ポン酢', amount: '大さじ1' },
      { name: '大根おろし', amount: '適量' },
    ],
    steps: [
      '豆腐の水気を切り、玉ねぎはみじん切り',
      '豆腐、ひき肉、玉ねぎ、パン粉、卵を混ぜる',
      '成形してフライパンで焼く',
      '大根おろしとポン酢で食べる',
    ],
    salt_tips: ['ポン酢と大根おろしでさっぱり', 'ソースより塩分控えめ'],
    sugar_tips: ['豆腐でかさ増しして低糖質'],
  },
  {
    id: 'dinner-main-003',
    name: '鶏むね肉の生姜焼き（減塩）',
    category: 'dinner_main',
    cooking_time_min: 20,
    calories: 200,
    salt_g: 1.0,
    carbs_g: 5,
    protein_g: 25,
    fiber_g: 1,
    potassium_mg: 350,
    ingredients: [
      { name: '鶏むね肉', amount: '1枚' },
      { name: '生姜', amount: '1かけ' },
      { name: '薄口醤油', amount: '小さじ1' },
      { name: '酒', amount: '大さじ1' },
      { name: 'みりん', amount: '小さじ1' },
      { name: 'キャベツ', amount: '2枚' },
    ],
    steps: [
      '鶏肉を削ぎ切りにする',
      '生姜をすりおろし、調味料と混ぜる',
      '鶏肉を焼き、タレを絡める',
      '千切りキャベツを添える',
    ],
    salt_tips: ['生姜の風味で醤油を減らせる'],
    sugar_tips: ['鶏むね肉は高たんぱく低脂質'],
  },
  {
    id: 'dinner-main-004',
    name: 'さばの味噌煮（減塩）',
    category: 'dinner_main',
    cooking_time_min: 25,
    calories: 280,
    salt_g: 1.5,
    carbs_g: 8,
    protein_g: 20,
    fiber_g: 1,
    potassium_mg: 350,
    ingredients: [
      { name: 'さば切り身', amount: '2切れ' },
      { name: '味噌', amount: '大さじ1' },
      { name: '酒', amount: '大さじ2' },
      { name: 'みりん', amount: '大さじ1' },
      { name: '生姜', amount: '1かけ' },
      { name: '水', amount: '100ml' },
    ],
    steps: [
      'さばに熱湯をかけて臭みを取る',
      '生姜はスライス',
      '調味料と水を煮立て、さばを入れる',
      '落とし蓋をして15分煮る',
    ],
    salt_tips: ['味噌は控えめ、生姜で風味UP'],
    sugar_tips: ['さばはDHA・EPAが豊富'],
  },
  {
    id: 'dinner-main-005',
    name: '肉豆腐',
    category: 'dinner_main',
    cooking_time_min: 20,
    calories: 250,
    salt_g: 1.2,
    carbs_g: 10,
    protein_g: 22,
    fiber_g: 2,
    potassium_mg: 400,
    ingredients: [
      { name: '牛薄切り肉', amount: '100g' },
      { name: '木綿豆腐', amount: '1/2丁' },
      { name: '長ネギ', amount: '1/2本' },
      { name: 'しらたき', amount: '100g' },
      { name: 'だし汁', amount: '200ml' },
      { name: '薄口醤油', amount: '小さじ2' },
      { name: 'みりん', amount: '大さじ1' },
    ],
    steps: [
      '豆腐は大きめに切り、ネギは斜め切り',
      'しらたきは下茹でする',
      'だし汁で肉と野菜を煮る',
      '調味料を加えて味を染み込ませる',
    ],
    salt_tips: ['だしを効かせて醤油控えめ'],
    sugar_tips: ['しらたきでかさ増し'],
  },
  {
    id: 'dinner-main-006',
    name: 'アジの塩焼き（塩控えめ）',
    category: 'dinner_main',
    cooking_time_min: 20,
    calories: 150,
    salt_g: 0.8,
    carbs_g: 1,
    protein_g: 20,
    fiber_g: 0,
    potassium_mg: 350,
    ingredients: [
      { name: 'アジ（開き）', amount: '1尾' },
      { name: '大根おろし', amount: '適量' },
      { name: 'すだち', amount: '1/2個' },
    ],
    steps: [
      'アジをグリルで焼く（塩は振らない）',
      '大根おろしとすだちを添える',
    ],
    salt_tips: ['開きは既に塩分あり、追加の塩不要', 'すだちで爽やかに'],
    sugar_tips: [],
  },
  {
    id: 'dinner-main-007',
    name: '鶏と野菜の蒸し煮',
    category: 'dinner_main',
    cooking_time_min: 30,
    calories: 220,
    salt_g: 1.0,
    carbs_g: 12,
    protein_g: 22,
    fiber_g: 4,
    potassium_mg: 600,
    ingredients: [
      { name: '鶏もも肉', amount: '150g' },
      { name: 'キャベツ', amount: '2枚' },
      { name: '人参', amount: '1/4本' },
      { name: 'しめじ', amount: '1/2パック' },
      { name: '酒', amount: '大さじ2' },
      { name: 'ポン酢', amount: '大さじ1' },
    ],
    steps: [
      '鶏肉は一口大に切る',
      '野菜を食べやすい大きさに切る',
      'フライパンに野菜、鶏肉、酒を入れ蓋をして蒸す',
      'ポン酢をかけて食べる',
    ],
    salt_tips: ['蒸し調理で素材の旨味を引き出す', 'ポン酢は控えめに'],
    sugar_tips: ['野菜たっぷりで満足感UP'],
  },
  {
    id: 'dinner-main-008',
    name: 'ぶりの照り焼き（減塩）',
    category: 'dinner_main',
    cooking_time_min: 20,
    calories: 280,
    salt_g: 1.2,
    carbs_g: 8,
    protein_g: 22,
    fiber_g: 0,
    potassium_mg: 400,
    ingredients: [
      { name: 'ぶり切り身', amount: '1切れ' },
      { name: '薄口醤油', amount: '小さじ1' },
      { name: 'みりん', amount: '大さじ1' },
      { name: '酒', amount: '大さじ1' },
      { name: '生姜汁', amount: '小さじ1' },
    ],
    steps: [
      'ぶりを焼き色がつくまで焼く',
      '調味料を合わせて加える',
      'タレを絡めながら煮詰める',
    ],
    salt_tips: ['みりんと酒で甘みを出し醤油を減らす'],
    sugar_tips: [],
  },
  {
    id: 'dinner-main-009',
    name: '麻婆豆腐（減塩・辛くない）',
    category: 'dinner_main',
    cooking_time_min: 20,
    calories: 250,
    salt_g: 1.5,
    carbs_g: 12,
    protein_g: 18,
    fiber_g: 2,
    potassium_mg: 350,
    ingredients: [
      { name: '木綿豆腐', amount: '1丁' },
      { name: '豚ひき肉', amount: '80g' },
      { name: '長ネギ', amount: '1/2本' },
      { name: '生姜', amount: '1かけ' },
      { name: '味噌', amount: '小さじ2' },
      { name: '鶏がらスープの素（減塩）', amount: '小さじ1/2' },
      { name: '水溶き片栗粉', amount: '適量' },
    ],
    steps: [
      '豆腐は水切りして一口大に切る',
      'ひき肉、ネギ、生姜を炒める',
      '水、味噌、スープの素を加える',
      '豆腐を入れて煮込み、とろみをつける',
    ],
    salt_tips: ['豆板醤を使わず味噌ベースで', '辛くないので血圧にも優しい'],
    sugar_tips: [],
  },
  {
    id: 'dinner-main-010',
    name: '野菜たっぷり豚しゃぶ',
    category: 'dinner_main',
    cooking_time_min: 20,
    calories: 300,
    salt_g: 1.0,
    carbs_g: 8,
    protein_g: 22,
    fiber_g: 4,
    potassium_mg: 500,
    ingredients: [
      { name: '豚ロースしゃぶしゃぶ用', amount: '100g' },
      { name: 'レタス', amount: '3枚' },
      { name: 'もやし', amount: '1/2袋' },
      { name: '水菜', amount: '1/4束' },
      { name: 'ポン酢', amount: '大さじ1' },
      { name: 'ごまだれ（減塩）', amount: '大さじ1' },
    ],
    steps: [
      '野菜を食べやすい大きさにする',
      '豚肉を湯通しする',
      '野菜と豚肉を皿に盛る',
      'タレをつけて食べる',
    ],
    salt_tips: ['タレは少量ずつつける'],
    sugar_tips: ['野菜から先に食べる'],
  },

  // === 夕食副菜（15分以内） ===
  {
    id: 'dinner-side-001',
    name: 'ほうれん草の胡麻和え',
    category: 'dinner_side',
    cooking_time_min: 10,
    calories: 60,
    salt_g: 0.4,
    carbs_g: 4,
    protein_g: 4,
    fiber_g: 3,
    potassium_mg: 500,
    ingredients: [
      { name: 'ほうれん草', amount: '1/2束' },
      { name: 'すりごま', amount: '大さじ1' },
      { name: '薄口醤油', amount: '小さじ1/2' },
      { name: '砂糖', amount: '小さじ1/4' },
    ],
    steps: [
      'ほうれん草を茹でて水にとる',
      '水気を絞り3cm長さに切る',
      '調味料で和える',
    ],
    salt_tips: ['ごまの風味で醤油控えめ'],
    sugar_tips: [],
  },
  {
    id: 'dinner-side-002',
    name: 'きゅうりの酢の物',
    category: 'dinner_side',
    cooking_time_min: 8,
    calories: 20,
    salt_g: 0.3,
    carbs_g: 4,
    protein_g: 1,
    fiber_g: 1,
    potassium_mg: 150,
    ingredients: [
      { name: 'きゅうり', amount: '1本' },
      { name: '酢', amount: '大さじ1' },
      { name: '砂糖', amount: '小さじ1/2' },
      { name: '塩', amount: 'ひとつまみ' },
    ],
    steps: [
      'きゅうりを薄切りにする',
      '塩少々で揉んで水気を出す',
      '酢と砂糖で和える',
    ],
    salt_tips: ['塩は最小限、酢でさっぱり'],
    sugar_tips: ['砂糖は控えめに'],
  },
  {
    id: 'dinner-side-003',
    name: 'ブロッコリーのおかか和え',
    category: 'dinner_side',
    cooking_time_min: 8,
    calories: 35,
    salt_g: 0.4,
    carbs_g: 4,
    protein_g: 4,
    fiber_g: 4,
    potassium_mg: 350,
    ingredients: [
      { name: 'ブロッコリー', amount: '1/2株' },
      { name: 'かつお節', amount: '1パック' },
      { name: '薄口醤油', amount: '小さじ1/2' },
    ],
    steps: [
      'ブロッコリーを小房に分け茹でる',
      '水気を切り、かつお節と醤油で和える',
    ],
    salt_tips: ['かつお節の旨味で醤油控えめ'],
    sugar_tips: [],
  },
  {
    id: 'dinner-side-004',
    name: 'トマトスライス',
    category: 'dinner_side',
    cooking_time_min: 3,
    calories: 25,
    salt_g: 0,
    carbs_g: 5,
    protein_g: 1,
    fiber_g: 1,
    potassium_mg: 250,
    ingredients: [
      { name: 'トマト', amount: '1個' },
      { name: 'オリーブオイル', amount: '小さじ1/2' },
      { name: '黒こしょう', amount: '少々' },
    ],
    steps: [
      'トマトを輪切りにする',
      'オリーブオイルとこしょうをかける',
    ],
    salt_tips: ['塩なしでもオリーブオイルで美味しい'],
    sugar_tips: ['トマトはリコピン豊富'],
  },
  {
    id: 'dinner-side-005',
    name: 'もずく酢',
    category: 'dinner_side',
    cooking_time_min: 2,
    calories: 10,
    salt_g: 0.5,
    carbs_g: 2,
    protein_g: 0,
    fiber_g: 1,
    potassium_mg: 100,
    ingredients: [
      { name: '市販もずく酢', amount: '1パック' },
      { name: 'きゅうり', amount: '少々' },
    ],
    steps: [
      'きゅうりを薄切りにする',
      'もずく酢と和える',
    ],
    salt_tips: ['市販品は塩分表示を確認'],
    sugar_tips: ['食物繊維が豊富'],
  },
  {
    id: 'dinner-side-006',
    name: 'アボカドサラダ',
    category: 'dinner_side',
    cooking_time_min: 5,
    calories: 120,
    salt_g: 0.2,
    carbs_g: 5,
    protein_g: 2,
    fiber_g: 4,
    potassium_mg: 400,
    ingredients: [
      { name: 'アボカド', amount: '1/2個' },
      { name: 'レモン汁', amount: '小さじ1' },
      { name: '黒こしょう', amount: '少々' },
    ],
    steps: [
      'アボカドを一口大に切る',
      'レモン汁とこしょうをかける',
    ],
    salt_tips: ['レモンで塩なしでも美味しい', 'カリウムが豊富'],
    sugar_tips: [],
  },
  {
    id: 'dinner-side-007',
    name: 'いんげんのごま和え',
    category: 'dinner_side',
    cooking_time_min: 10,
    calories: 45,
    salt_g: 0.3,
    carbs_g: 5,
    protein_g: 2,
    fiber_g: 2,
    potassium_mg: 200,
    ingredients: [
      { name: 'いんげん', amount: '10本' },
      { name: 'すりごま', amount: '大さじ1' },
      { name: '薄口醤油', amount: '小さじ1/2' },
    ],
    steps: [
      'いんげんを塩なしで茹でる',
      '3cm長さに切る',
      'ごまと醤油で和える',
    ],
    salt_tips: ['茹でる時に塩を入れない'],
    sugar_tips: [],
  },
  {
    id: 'dinner-side-008',
    name: '白菜の浅漬け',
    category: 'dinner_side',
    cooking_time_min: 5,
    calories: 15,
    salt_g: 0.4,
    carbs_g: 3,
    protein_g: 1,
    fiber_g: 1,
    potassium_mg: 200,
    ingredients: [
      { name: '白菜', amount: '2枚' },
      { name: '塩', amount: '少々' },
      { name: '塩昆布', amount: '少々' },
    ],
    steps: [
      '白菜を一口大に切る',
      '塩と塩昆布を加えて揉む',
      '少し置いて味をなじませる',
    ],
    salt_tips: ['塩と塩昆布は控えめに'],
    sugar_tips: [],
  },
  {
    id: 'dinner-side-009',
    name: 'かぶの柚子風味',
    category: 'dinner_side',
    cooking_time_min: 10,
    calories: 20,
    salt_g: 0.3,
    carbs_g: 4,
    protein_g: 1,
    fiber_g: 1,
    potassium_mg: 200,
    ingredients: [
      { name: 'かぶ', amount: '1個' },
      { name: '柚子の皮', amount: '少々' },
      { name: '酢', amount: '大さじ1' },
    ],
    steps: [
      'かぶを薄切りにする',
      '柚子の皮を細切り',
      '酢で和える',
    ],
    salt_tips: ['柚子の香りで塩なしでOK'],
    sugar_tips: [],
  },
  {
    id: 'dinner-side-010',
    name: 'にら玉',
    category: 'dinner_side',
    cooking_time_min: 8,
    calories: 120,
    salt_g: 0.5,
    carbs_g: 2,
    protein_g: 10,
    fiber_g: 1,
    potassium_mg: 250,
    ingredients: [
      { name: 'にら', amount: '1/2束' },
      { name: '卵', amount: '2個' },
      { name: 'ごま油', amount: '小さじ1' },
      { name: '薄口醤油', amount: '小さじ1/2' },
    ],
    steps: [
      'にらを3cm長さに切る',
      '卵を溶く',
      'ごま油でにらを炒め、卵を加えて半熟に仕上げる',
      '醤油を回しかける',
    ],
    salt_tips: ['にらの風味で醤油控えめ'],
    sugar_tips: [],
  },

  // === 汁物 ===
  {
    id: 'soup-001',
    name: '具沢山豚汁（減塩）',
    category: 'soup',
    cooking_time_min: 25,
    calories: 150,
    salt_g: 1.2,
    carbs_g: 12,
    protein_g: 10,
    fiber_g: 3,
    potassium_mg: 500,
    ingredients: [
      { name: '豚バラ薄切り', amount: '50g' },
      { name: '大根', amount: '3cm' },
      { name: '人参', amount: '1/4本' },
      { name: 'こんにゃく', amount: '1/4枚' },
      { name: 'ごぼう', amount: '1/4本' },
      { name: '味噌', amount: '大さじ1' },
      { name: 'だしパック', amount: '2パック' },
      { name: '水', amount: '400ml' },
    ],
    steps: [
      'だしパック2つで濃いめにだしを取る',
      '野菜と肉を入れて煮る',
      '火を止めて味噌を溶く',
    ],
    salt_tips: ['だしを濃くして味噌半量', '具を多くして汁を少なめに'],
    sugar_tips: [],
  },
  {
    id: 'soup-002',
    name: 'わかめと豆腐の味噌汁',
    category: 'soup',
    cooking_time_min: 10,
    calories: 50,
    salt_g: 1.0,
    carbs_g: 4,
    protein_g: 4,
    fiber_g: 1,
    potassium_mg: 250,
    ingredients: [
      { name: '豆腐', amount: '1/4丁' },
      { name: 'わかめ', amount: '少々' },
      { name: '味噌', amount: '大さじ1' },
      { name: 'だしパック', amount: '2パック' },
      { name: '水', amount: '300ml' },
    ],
    steps: [
      'だしパック2つでだしを取る',
      '豆腐とわかめを入れて温める',
      '火を止めて味噌を溶く',
    ],
    salt_tips: ['味噌は大さじ1まで'],
    sugar_tips: [],
  },
  {
    id: 'soup-003',
    name: '野菜たっぷりスープ',
    category: 'soup',
    cooking_time_min: 20,
    calories: 60,
    salt_g: 0.8,
    carbs_g: 10,
    protein_g: 2,
    fiber_g: 3,
    potassium_mg: 400,
    ingredients: [
      { name: 'キャベツ', amount: '2枚' },
      { name: '人参', amount: '1/4本' },
      { name: '玉ねぎ', amount: '1/4個' },
      { name: 'コンソメ（減塩）', amount: '1/2個' },
      { name: '水', amount: '400ml' },
      { name: 'こしょう', amount: '少々' },
    ],
    steps: [
      '野菜を食べやすい大きさに切る',
      '水とコンソメで煮る',
      'こしょうで味を調える',
    ],
    salt_tips: ['減塩コンソメを使用', '野菜の旨味を活かす'],
    sugar_tips: [],
  },
  {
    id: 'soup-004',
    name: 'きのこ汁',
    category: 'soup',
    cooking_time_min: 15,
    calories: 40,
    salt_g: 0.8,
    carbs_g: 5,
    protein_g: 3,
    fiber_g: 2,
    potassium_mg: 300,
    ingredients: [
      { name: 'しめじ', amount: '1/2パック' },
      { name: 'えのき', amount: '1/2袋' },
      { name: 'まいたけ', amount: '1/2パック' },
      { name: '味噌', amount: '大さじ1' },
      { name: 'だしパック', amount: '2パック' },
      { name: '水', amount: '300ml' },
      { name: '青ネギ', amount: '少々' },
    ],
    steps: [
      'だしパック2つでだしを取る',
      'きのこを入れて煮る',
      '火を止めて味噌を溶き、ネギを散らす',
    ],
    salt_tips: ['きのこの旨味で減塩'],
    sugar_tips: [],
  },
  {
    id: 'soup-005',
    name: 'なめこ汁',
    category: 'soup',
    cooking_time_min: 10,
    calories: 35,
    salt_g: 0.9,
    carbs_g: 4,
    protein_g: 3,
    fiber_g: 1,
    potassium_mg: 200,
    ingredients: [
      { name: 'なめこ', amount: '1袋' },
      { name: '豆腐', amount: '1/4丁' },
      { name: '味噌', amount: '大さじ1' },
      { name: 'だしパック', amount: '2パック' },
      { name: '水', amount: '300ml' },
    ],
    steps: [
      'だしを取る',
      'なめこと豆腐を入れて温める',
      '味噌を溶く',
    ],
    salt_tips: ['なめこのとろみで満足感UP'],
    sugar_tips: [],
  },
  {
    id: 'soup-006',
    name: 'あさりの味噌汁',
    category: 'soup',
    cooking_time_min: 15,
    calories: 40,
    salt_g: 1.2,
    carbs_g: 3,
    protein_g: 5,
    fiber_g: 0,
    potassium_mg: 250,
    ingredients: [
      { name: 'あさり', amount: '100g' },
      { name: '長ネギ', amount: '少々' },
      { name: '味噌', amount: '大さじ1弱' },
      { name: '水', amount: '300ml' },
    ],
    steps: [
      'あさりを砂抜きする',
      '水からあさりを煮て、口が開いたら火を止める',
      '味噌を溶き、ネギを散らす',
    ],
    salt_tips: ['あさりの旨味が出るので味噌控えめ'],
    sugar_tips: [],
  },
  {
    id: 'soup-007',
    name: 'かきたま汁',
    category: 'soup',
    cooking_time_min: 10,
    calories: 60,
    salt_g: 0.7,
    carbs_g: 2,
    protein_g: 5,
    fiber_g: 0,
    potassium_mg: 150,
    ingredients: [
      { name: '卵', amount: '1個' },
      { name: 'だし汁', amount: '300ml' },
      { name: '薄口醤油', amount: '小さじ1' },
      { name: '水溶き片栗粉', amount: '少々' },
      { name: '三つ葉', amount: '少々' },
    ],
    steps: [
      'だし汁を沸かし、醤油で味付け',
      '水溶き片栗粉でとろみをつける',
      '溶き卵を流し入れ、三つ葉を散らす',
    ],
    salt_tips: ['だしを効かせて醤油控えめ'],
    sugar_tips: [],
  },
  {
    id: 'soup-008',
    name: '大根と油揚げの味噌汁',
    category: 'soup',
    cooking_time_min: 15,
    calories: 60,
    salt_g: 1.0,
    carbs_g: 6,
    protein_g: 3,
    fiber_g: 1,
    potassium_mg: 250,
    ingredients: [
      { name: '大根', amount: '3cm' },
      { name: '油揚げ', amount: '1/2枚' },
      { name: '味噌', amount: '大さじ1' },
      { name: 'だしパック', amount: '2パック' },
      { name: '水', amount: '300ml' },
    ],
    steps: [
      'だしを取り、大根のいちょう切りを煮る',
      '油揚げを加える',
      '味噌を溶く',
    ],
    salt_tips: ['だしを濃くして味噌半量'],
    sugar_tips: [],
  },
  {
    id: 'soup-009',
    name: 'キャベツとベーコンのスープ',
    category: 'soup',
    cooking_time_min: 15,
    calories: 80,
    salt_g: 1.0,
    carbs_g: 6,
    protein_g: 4,
    fiber_g: 2,
    potassium_mg: 250,
    ingredients: [
      { name: 'キャベツ', amount: '2枚' },
      { name: 'ベーコン（減塩）', amount: '1枚' },
      { name: 'コンソメ（減塩）', amount: '1/2個' },
      { name: '水', amount: '400ml' },
      { name: '黒こしょう', amount: '少々' },
    ],
    steps: [
      'キャベツをざく切り、ベーコンは1cm幅に切る',
      '水とコンソメで煮る',
      'こしょうで味を調える',
    ],
    salt_tips: ['減塩ベーコン・コンソメを選ぶ'],
    sugar_tips: [],
  },
  {
    id: 'soup-010',
    name: 'ほうれん草の味噌汁',
    category: 'soup',
    cooking_time_min: 10,
    calories: 40,
    salt_g: 1.0,
    carbs_g: 4,
    protein_g: 3,
    fiber_g: 2,
    potassium_mg: 400,
    ingredients: [
      { name: 'ほうれん草', amount: '1/2束' },
      { name: '油揚げ', amount: '1/2枚' },
      { name: '味噌', amount: '大さじ1' },
      { name: 'だしパック', amount: '2パック' },
      { name: '水', amount: '300ml' },
    ],
    steps: [
      'だしを取る',
      '油揚げとほうれん草を入れて煮る',
      '味噌を溶く',
    ],
    salt_tips: ['ほうれん草でカリウム補給'],
    sugar_tips: [],
  },
];

// 外食プリセット
const eatingOutPresets = [
  { id: 'eat-001', name: 'ラーメン（1杯）', calories: 500, salt_g: 6.0, carbs_g: 70, protein_g: 15, warning: 'ラーメンは1杯で塩分約6g。これだけで1日分です。スープは残しましょう。' },
  { id: 'eat-002', name: '牛丼（並）', calories: 650, salt_g: 3.5, carbs_g: 90, protein_g: 20, warning: '牛丼は糖質が多めです。サラダを追加し、ご飯を少なめに。' },
  { id: 'eat-003', name: 'カレーライス', calories: 700, salt_g: 3.0, carbs_g: 100, protein_g: 15, warning: 'カレーは糖質が多め。ご飯少なめ、サラダ追加を。' },
  { id: 'eat-004', name: 'かつ丼', calories: 900, salt_g: 4.0, carbs_g: 100, protein_g: 30, warning: '高カロリー・高糖質。たまのご褒美に。' },
  { id: 'eat-005', name: 'うどん（かけ）', calories: 300, salt_g: 5.0, carbs_g: 60, protein_g: 8, warning: 'うどんつゆは塩分高め。飲み干さないように。' },
  { id: 'eat-006', name: 'そば（かけ）', calories: 280, salt_g: 4.5, carbs_g: 50, protein_g: 10, warning: 'つゆは飲み干さないように。' },
  { id: 'eat-007', name: 'ハンバーガーセット', calories: 800, salt_g: 3.0, carbs_g: 80, protein_g: 25, warning: '脂質と糖質が多め。サイドはサラダに変更を。' },
  { id: 'eat-008', name: '唐揚げ定食', calories: 750, salt_g: 3.5, carbs_g: 80, protein_g: 30, warning: '揚げ物は脂質高め。ご飯少なめで。' },
  { id: 'eat-009', name: '焼肉定食', calories: 700, salt_g: 3.0, carbs_g: 70, protein_g: 25, warning: 'たんぱく質は多いがタレの塩分に注意。' },
  { id: 'eat-010', name: 'パスタ（トマトソース）', calories: 600, salt_g: 2.5, carbs_g: 80, protein_g: 15, warning: '糖質が多め。サラダを先に食べて。' },
  { id: 'eat-011', name: 'コンビニおにぎり（1個）', calories: 180, salt_g: 0.8, carbs_g: 35, protein_g: 4, warning: '手軽だが1個では栄養が偏りがち。' },
  { id: 'eat-012', name: 'コンビニサラダ', calories: 80, salt_g: 0.5, carbs_g: 8, protein_g: 3, warning: 'ドレッシングは半量で。' },
  { id: 'eat-013', name: 'サンドイッチ', calories: 300, salt_g: 1.5, carbs_g: 30, protein_g: 10, warning: '比較的バランス良し。' },
  { id: 'eat-014', name: '寿司（8貫）', calories: 400, salt_g: 3.0, carbs_g: 60, protein_g: 20, warning: '醤油は少なめに。ガリで塩分追加に注意。' },
  { id: 'eat-015', name: 'ピザ（2切れ）', calories: 500, salt_g: 2.5, carbs_g: 50, protein_g: 15, warning: 'チーズの塩分に注意。野菜も一緒に。' },
];

// 日次ミッションのテンプレート
const missionTemplates = [
  '夕食の白米を一口分（20g）減らす',
  '水を1杯多く飲む',
  'エレベーターの代わりに1フロアだけ階段を使う',
  '食事の最初に野菜を3口食べる',
  '座ったまま3分間のストレッチをする',
  '深呼吸を5回する',
  'お菓子を1つ我慢する',
  '減塩醤油を使う',
  '味噌汁の味噌を少し減らす',
  '間食をしない',
  '夜22時までにスマホを置く',
  '朝の血圧を測る',
  '今日食べたものを全部記録する',
  'CPAPを使って寝る',
  '食事をゆっくり20分かけて食べる',
];

export function seedDatabase() {
  const db = getDb();

  // レシピを挿入
  const insertRecipe = db.prepare(`
    INSERT OR REPLACE INTO recipes
    (id, name, category, cooking_time_min, calories, salt_g, carbs_g, protein_g, fiber_g, potassium_mg, ingredients_json, steps_json, salt_tips_json, sugar_tips_json)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  for (const recipe of recipes) {
    insertRecipe.run(
      recipe.id,
      recipe.name,
      recipe.category,
      recipe.cooking_time_min,
      recipe.calories,
      recipe.salt_g,
      recipe.carbs_g,
      recipe.protein_g,
      recipe.fiber_g,
      recipe.potassium_mg,
      JSON.stringify(recipe.ingredients),
      JSON.stringify(recipe.steps),
      JSON.stringify(recipe.salt_tips),
      JSON.stringify(recipe.sugar_tips)
    );
  }

  // 外食プリセットを挿入
  const insertPreset = db.prepare(`
    INSERT OR REPLACE INTO eating_out_presets
    (id, name, calories, salt_g, carbs_g, protein_g, warning)
    VALUES (?, ?, ?, ?, ?, ?, ?)
  `);

  for (const preset of eatingOutPresets) {
    insertPreset.run(
      preset.id,
      preset.name,
      preset.calories,
      preset.salt_g,
      preset.carbs_g,
      preset.protein_g,
      preset.warning
    );
  }

  console.log(`Seeded ${recipes.length} recipes and ${eatingOutPresets.length} eating out presets`);
}

export { missionTemplates };
